name: tests

on:
  push:
    paths-ignore:
      - README.md
      - .devcontainer/**/*.*
      - ".vscode/**/*.*"
      - .gitignore
      - pyproject.toml
  pull_request:
    types:  # avoid double runs in open pr
      - opened
      - reopened
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          echo ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }} >> .env
          echo MILLION_VERIFIER_KEY=${{ secrets.MILLION_VERIFIER_KEY }} >> .env
          echo NUMVERIFY_KEY=${{ secrets.NUMVERIFY_KEY }} >> .env
          echo LOGFIRE_WRITE_TOKEN=${{ secrets.LOGFIRE_WRITE_TOKEN }} >> .env
          echo FOLLOWUPBOSS_API_KEY=${{ secrets.FOLLOWUPBOSS_API_KEY }} >> .env
          echo FOLLOWUPBOSS_SYSTEM=${{ secrets.FOLLOWUPBOSS_SYSTEM }} >> .env
          echo FOLLOWUPBOSS_SYSTEM_KEY=${{ secrets.FOLLOWUPBOSS_SYSTEM_KEY }} >> .env
          echo PERPLEXITY_API_KEY=${{ secrets.PERPLEXITY_API_KEY }} >> .env
          echo SCRAPYBARA_API_KEY=${{ secrets.SCRAPYBARA_API_KEY }} >> .env

      - name: Build Docker container
        run: docker build -t real-intent .
        
      - name: Run tests inside container
        run: docker run real-intent sh -c "pip install --no-cache-dir -r tests/requirements.txt && pytest"
